package com.gestionplanillas.application.views.formularionuevoempleado;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.H5;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.auth.AnonymousAllowed;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import java.util.ArrayList;
import java.util.List;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Formulario Nuevo Empleado")
@Route("form-nuevo-empleado")
@Menu(order = 2, icon = LineAwesomeIconUrl.USER_PLUS_SOLID)
@AnonymousAllowed
public class FormularioNuevoEmpleadoView extends Composite<VerticalLayout> {

    public FormularioNuevoEmpleadoView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H2 h2 = new H2();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        HorizontalLayout layoutRow = new HorizontalLayout();
        H3 h3 = new H3();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        TextField textField = new TextField();
        TextField textField2 = new TextField();
        TextField textField3 = new TextField();
        TextField textField4 = new TextField();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        TextField textField5 = new TextField();
        TextField textField6 = new TextField();
        TextField textField7 = new TextField();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        TextField textField8 = new TextField();
        ComboBox comboBox = new ComboBox();
        ComboBox comboBox2 = new ComboBox();
        TextField textField9 = new TextField();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        EmailField emailField = new EmailField();
        TextArea textArea = new TextArea();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H3 h32 = new H3();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        TextField textField10 = new TextField();
        TextField textField11 = new TextField();
        TextField textField12 = new TextField();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        H3 h33 = new H3();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        TextField textField13 = new TextField();
        ComboBox comboBox3 = new ComboBox();
        ComboBox comboBox4 = new ComboBox();
        HorizontalLayout layoutRow8 = new HorizontalLayout();
        TextField textField14 = new TextField();
        ComboBox comboBox5 = new ComboBox();
        TextField textField15 = new TextField();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        HorizontalLayout layoutRow9 = new HorizontalLayout();
        HorizontalLayout layoutRow10 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Button buttonSecondary = new Button();
        HorizontalLayout layoutRow11 = new HorizontalLayout();
        H5 h5 = new H5();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutColumn2.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.setWidth("100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        h2.setText("Formulario: Ingreso de Nuevo Empleado");
        h2.setWidth("max-content");
        layoutColumn3.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        layoutRow.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.getStyle().set("flex-grow", "1");
        h3.setText("Datos Personales del Empleado");
        h3.setWidth("max-content");
        layoutRow2.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.setHeight("min-content");
        layoutRow2.setAlignItems(Alignment.START);
        layoutRow2.setJustifyContentMode(JustifyContentMode.CENTER);
        textField.setLabel("Primer Nombre");
        textField.setWidth("150px");
        textField2.setLabel("Segundo Nombre");
        textField2.setWidth("150px");
        textField3.setLabel("Primer Apellido");
        textField3.setWidth("150px");
        textField4.setLabel("Segundo Apellido");
        textField4.setWidth("150px");
        layoutRow3.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.setHeight("min-content");
        layoutRow3.setAlignItems(Alignment.CENTER);
        layoutRow3.setJustifyContentMode(JustifyContentMode.CENTER);
        textField5.setLabel("Código empresarial Empleado");
        textField5.setWidth("220px");
        textField6.setLabel("DUI del Empleado");
        textField6.setWidth("200px");
        textField7.setLabel("NIT del Empleado");
        textField7.setWidth("200px");
        layoutRow4.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.setHeight("min-content");
        layoutRow4.setAlignItems(Alignment.START);
        layoutRow4.setJustifyContentMode(JustifyContentMode.CENTER);
        textField8.setLabel("Fecha de Nacimiento");
        textField8.setWidth("150px");
        comboBox.setLabel("Lugar de Nacimiento");
        comboBox.setWidth("150px");
        setComboBoxSampleData(comboBox);
        comboBox2.setLabel("Estado Civil");
        comboBox2.setWidth("150px");
        setComboBoxSampleData(comboBox2);
        textField9.setLabel("Teléfono");
        textField9.setWidth("150px");
        layoutRow5.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow5);
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.setWidth("100%");
        layoutRow5.setHeight("min-content");
        layoutRow5.setAlignItems(Alignment.START);
        layoutRow5.setJustifyContentMode(JustifyContentMode.CENTER);
        emailField.setLabel("Email");
        emailField.setWidth("225px");
        textArea.setLabel("Dirección del Empleado");
        textArea.setWidth("400px");
        layoutColumn4.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        h32.setText("Datos Bancarios y Prestaciones de Ley");
        h32.setWidth("max-content");
        layoutRow6.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow6);
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.setWidth("100%");
        layoutRow6.getStyle().set("flex-grow", "1");
        layoutRow6.setAlignItems(Alignment.START);
        layoutRow6.setJustifyContentMode(JustifyContentMode.CENTER);
        textField10.setLabel("Número de Cuenta Bancaria");
        textField10.setWidth("220px");
        textField11.setLabel("Número de Afiliación ISSS");
        textField11.setWidth("200px");
        textField12.setLabel("Número de Afiliación AFP");
        textField12.setWidth("200px");
        layoutColumn5.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.setWidth("100%");
        layoutColumn5.getStyle().set("flex-grow", "1");
        h33.setText("Datos del Puesto del Empleado");
        h33.setWidth("max-content");
        layoutRow7.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow7);
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.setWidth("100%");
        layoutRow7.setHeight("min-content");
        layoutRow7.setAlignItems(Alignment.START);
        layoutRow7.setJustifyContentMode(JustifyContentMode.CENTER);
        textField13.setLabel("Cargo Asignado");
        textField13.setWidth("220px");
        comboBox3.setLabel("Departamento");
        comboBox3.setWidth("200px");
        setComboBoxSampleData(comboBox3);
        comboBox4.setLabel("Tipo de Contrato");
        comboBox4.setWidth("200px");
        setComboBoxSampleData(comboBox4);
        layoutRow8.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow8);
        layoutRow8.addClassName(Gap.MEDIUM);
        layoutRow8.setWidth("100%");
        layoutRow8.setHeight("min-content");
        layoutRow8.setAlignItems(Alignment.START);
        layoutRow8.setJustifyContentMode(JustifyContentMode.CENTER);
        textField14.setLabel("Fecha de Ingreso");
        textField14.setWidth("220px");
        comboBox5.setLabel("Tipo de Jornada");
        comboBox5.setWidth("200px");
        setComboBoxSampleData(comboBox5);
        textField15.setLabel("Salario a Pagar");
        textField15.setWidth("200px");
        layoutColumn6.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn6);
        layoutColumn6.setWidth("100%");
        layoutColumn6.getStyle().set("flex-grow", "1");
        layoutRow9.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow9);
        layoutRow9.addClassName(Gap.MEDIUM);
        layoutRow9.setWidth("100%");
        layoutRow9.getStyle().set("flex-grow", "1");
        layoutRow10.setHeightFull();
        layoutRow9.setFlexGrow(1.0, layoutRow10);
        layoutRow10.addClassName(Gap.MEDIUM);
        layoutRow10.setWidth("100%");
        layoutRow10.setHeight("min-content");
        layoutRow10.setAlignItems(Alignment.CENTER);
        layoutRow10.setJustifyContentMode(JustifyContentMode.CENTER);
        buttonPrimary.setText("Agregar");
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonSecondary.setText("Cancelar");
        buttonSecondary.setWidth("min-content");
        layoutRow11.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow11);
        layoutRow11.addClassName(Gap.MEDIUM);
        layoutRow11.setWidth("100%");
        layoutRow11.getStyle().set("flex-grow", "1");
        layoutRow11.setAlignItems(Alignment.START);
        layoutRow11.setJustifyContentMode(JustifyContentMode.CENTER);
        h5.setText("Empleado agregado con Éxito");
        h5.setWidth("max-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(h2);
        layoutColumn2.add(layoutColumn3);
        layoutColumn3.add(layoutRow);
        layoutRow.add(h3);
        layoutColumn3.add(layoutRow2);
        layoutRow2.add(textField);
        layoutRow2.add(textField2);
        layoutRow2.add(textField3);
        layoutRow2.add(textField4);
        layoutColumn3.add(layoutRow3);
        layoutRow3.add(textField5);
        layoutRow3.add(textField6);
        layoutRow3.add(textField7);
        layoutColumn3.add(layoutRow4);
        layoutRow4.add(textField8);
        layoutRow4.add(comboBox);
        layoutRow4.add(comboBox2);
        layoutRow4.add(textField9);
        layoutColumn3.add(layoutRow5);
        layoutRow5.add(emailField);
        layoutRow5.add(textArea);
        layoutColumn2.add(layoutColumn4);
        layoutColumn4.add(h32);
        layoutColumn4.add(layoutRow6);
        layoutRow6.add(textField10);
        layoutRow6.add(textField11);
        layoutRow6.add(textField12);
        layoutColumn2.add(layoutColumn5);
        layoutColumn5.add(h33);
        layoutColumn5.add(layoutRow7);
        layoutRow7.add(textField13);
        layoutRow7.add(comboBox3);
        layoutRow7.add(comboBox4);
        layoutColumn5.add(layoutRow8);
        layoutRow8.add(textField14);
        layoutRow8.add(comboBox5);
        layoutRow8.add(textField15);
        layoutColumn2.add(layoutColumn6);
        layoutColumn6.add(layoutRow9);
        layoutRow9.add(layoutRow10);
        layoutRow10.add(buttonPrimary);
        layoutRow10.add(buttonSecondary);
        layoutColumn6.add(layoutRow11);
        layoutRow11.add(h5);
    }

    record SampleItem(String value, String label, Boolean disabled) {
    }

    private void setComboBoxSampleData(ComboBox comboBox) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        comboBox.setItems(sampleItems);
        comboBox.setItemLabelGenerator(item -> ((SampleItem) item).label());
    }
}
